#!/bin/sh
root=$(dirname "$0")
. "$root/common.sh"

rcfile="$confing_root/backlightrc.sh"
if [ ! -f "$rcfile" ]; then
    cat "$root/backlightrc.default.sh" > "$rcfile"
fi

# shellcheck source=src/control/backlightrc.default.sh
. "$rcfile"

tmp_value_file="$confing_root/.backlight-value-tmp"

get_brightness="perconf -m 0 -FM $backlight_path/max_brightness -Fc $backlight_path/brightness"
update_brightness="perconf -m 0 -FM $backlight_path/max_brightness -Fc $backlight_path/brightness -Fo $backlight_path/brightness"


value(){
    $get_brightness
}

set_value(){
    $update_brightness -s "$1"
}

change_value(){
    $update_brightness -i "$1"
}


c="$1"
shift
$c "$@"
