#!/bin/sh

battery_path="/sys/class/power_supply/BAT1"
charging_state="Charging"

value(){
    cat "$battery_path/capacity"
}

charging(){
    test "$(cat "$battery_path/status")" = "$charging_state"
}

c="$1"
shift
$c "$@"
