#!/bin/sh

value(){
    pamixer --get-volume
}

muted(){
    test "$(pamixer --get-mute)" = "true"
}

set_value(){
    pamixer --set-volume "$1"
}

change_value(){
    if [ "$1" -ge 0 ]; then
        pamixer --increase "$1"
    else
        pamixer --decrease "$(echo "$1" | cut -c2-)"
    fi
}

toggle_muted(){
    pamixer -t
    muted
}


c="$1"
shift
$c "$@"
