#!/bin/bash

path='/home/liava/Pictures/screenshots'
mkdir -p "$path"

instant=false
area=""
highlight=false

filename="$(date +"%Y-%m-%dT%H-%M-%SZ").png"
file="${path}/${filename}"

while [ $# -gt 0 ]; do
    arg="$1"
    case $arg in
        -i|--instant)
            instant=true
            ;;
        -a|--area)
            shift
            area="$1"
            ;;
        -h|--highlight)
            highlight=true
            ;;
        *)
            echo "Usage: screenshot [-i|--instant] [-a|--area <window|select>]"
            exit 1
    esac
    shift
done

feh_pid=""
if $instant && [ $area = "select" ]; then
	maim -u | feh -F - &
	feh_pid=$!

	while [ -z "$(xdotool search --pid "$feh_pid")" ]; do
    		sleep 0\.05
	done

	wid="$(xdotool search --pid "$feh_pid")"
	xdotool windowsize "$wid" 100% 100%
	xdotool windowmove "$wid" 0 0
fi

case $area in
	"window")
		maim -B -i $(xdotool getactivewindow) "$file"
		;;
	"select")
        if $highlight; then
            maim -B -s -l -c 1,0\.6,0,0\.4 "$file"
        else
            maim -B -s "$file"
        fi
		;;
	*)
		maim -B "$file"
		;;
esac

kill "$feh_pid" 2>/dev/null

if [ -f "$file" ]; then
	xclip -selection clipboard -target image/png -i "$file"
	echo -n "$file" | xclip -selection primary
fi
