#!/bin/sh

root=$(dirname "$0")
widget_name="$1"

widget_lock="/tmp/lde-widget-$widget_name.lock"

echo $(cat "$widget_lock" 2>/dev/null)

if kill -2 $(cat "$widget_lock" 2>/dev/null) 2>/dev/null; then
    echo "exit..."
else
    $root/run-widget "$widget_name" ${@:2} &
fi
